# Generated by Django 4.1.2 on 2022-11-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProcedenciaN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveAreaSIO', models.CharField(max_length=100, null=True)),
                ('nombreAreaSIO', models.CharField(max_length=100, null=True)),
                ('claveArea', models.CharField(max_length=100, null=True)),
                ('nombreArea', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AreaSIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaFin', models.DateTimeField(null=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('idArea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_AreaSIO', to='CATALOGOS.areas')),
            ],
        ),
        migrations.CreateModel(
            name='EstatusCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionesFinancieras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_registro', models.CharField(max_length=20, null=True)),
                ('denominacion_social', models.CharField(max_length=500)),
                ('nombre_corto', models.CharField(max_length=200, null=True)),
                ('rfc', models.CharField(max_length=20, null=True)),
                ('estatus', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Macroproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=256)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaFin', models.DateTimeField(null=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('idEstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_Catalogo_Macroproceso', to='CATALOGOS.estatuscatalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=256)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaFin', models.DateTimeField(null=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('idEstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_Catalogo_Proceso', to='CATALOGOS.estatuscatalogo')),
                ('idMacroproceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.macroproceso')),
            ],
        ),
        migrations.CreateModel(
            name='TipoOrdenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMacroproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaFin', models.DateTimeField(null=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('idEstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_Catalogo_TMacroproceso', to='CATALOGOS.estatuscatalogo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=10)),
                ('vistaAsesor', models.IntegerField(blank=True, null=True)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('idEstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_Catalogo_TipoDocumental', to='CATALOGOS.estatuscatalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=256)),
                ('cierreExplicito', models.IntegerField(null=True)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaFin', models.DateTimeField(null=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('idEstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_Catalogo_Serie', to='CATALOGOS.estatuscatalogo')),
                ('idOrdenamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.tipoordenamiento')),
                ('idProceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.proceso')),
            ],
        ),
        migrations.AddField(
            model_name='macroproceso',
            name='idTipoMacroproceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.tipomacroproceso'),
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=100, null=True)),
                ('idUsuarioCreador', models.CharField(blank=True, max_length=50, null=True)),
                ('idSubserie', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaApertura', models.DateTimeField(blank=True)),
                ('fechaCierre', models.DateTimeField(blank=True, null=True)),
                ('numeroLegajos', models.IntegerField(blank=True, null=True)),
                ('numeroFojas', models.IntegerField(blank=True, null=True)),
                ('resumenContenido', models.CharField(blank=True, max_length=600, null=True)),
                ('idAreaProcedenciaA', models.CharField(blank=True, max_length=500, null=True)),
                ('folioSIO', models.CharField(blank=True, max_length=500, null=True)),
                ('reclamante', models.CharField(blank=True, max_length=300, null=True)),
                ('idInstitucion', models.IntegerField(blank=True, null=True)),
                ('instanciaProceso', models.CharField(blank=True, max_length=10, null=True)),
                ('baseHistorico', models.CharField(blank=True, max_length=50, null=True)),
                ('pori', models.CharField(blank=True, max_length=20, null=True)),
                ('idUsuarioModificador', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('institucionMig', models.CharField(blank=True, max_length=700, null=True)),
                ('processInstanceIDRC', models.CharField(blank=True, max_length=50, null=True)),
                ('idAreaProcedenciaN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.areaprocedencian')),
                ('idAreaSIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.areasio')),
                ('idEstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_Catalogo_Expediente', to='CATALOGOS.estatusexpediente')),
                ('idMacroproceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.macroproceso')),
                ('idProceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.proceso')),
                ('idSerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.serie')),
                ('idTipoMacroproceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.tipomacroproceso')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-fechaCreacion'],
            },
        ),
        migrations.AddField(
            model_name='areasio',
            name='idEstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_Catalogo_AreaSIO', to='CATALOGOS.estatuscatalogo'),
        ),
    ]
