# Generated by Django 4.1.2 on 2022-11-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_expediente_options', to='CATALOGOS.areas')),
                ('idMacroproceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Macroproceso_options', to='CATALOGOS.macroproceso')),
                ('idProceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Proceso_options', to='CATALOGOS.proceso')),
                ('idSerie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Serie_options', to='CATALOGOS.serie')),
                ('idTipoMacroproceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoMacroproceso_expediente_options', to='CATALOGOS.tipomacroproceso')),
            ],
            options={
                'verbose_name': 'Add expediente option',
                'verbose_name_plural': 'Add expediente options',
                'ordering': ['-idArea'],
            },
        ),
    ]
