# Generated by Django 4.1.2 on 2022-11-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0002_expedienteoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasio',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
