# Generated by Django 4.1.2 on 2022-11-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0003_alter_areasio_fechaactualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macroproceso',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipomacroproceso',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
