# Generated by Django 4.1.2 on 2022-11-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0004_alter_macroproceso_fechaactualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='idAreaProcedenciaN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.areas'),
        ),
    ]
