# Generated by Django 4.1.2 on 2022-11-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0005_alter_expediente_idareaprocedencian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='idEstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Status_Catalogo_Expediente', to='CATALOGOS.estatusexpediente'),
        ),
    ]
