# Generated by Django 4.1.2 on 2022-11-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0007_alter_expediente_idestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='idEstatus',
        ),
    ]
