# Generated by Django 4.1.2 on 2022-11-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0008_remove_expediente_idestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='idEstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.estatusexpediente'),
        ),
    ]
