# Generated by Django 4.1.2 on 2022-11-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0010_tipodocumental_tipo_macroproceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumental',
            name='tipo_macroproceso',
        ),
    ]
