# Generated by Django 4.1.2 on 2022-12-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0011_remove_tipodocumental_tipo_macroproceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='formatoSoporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
