# Generated by Django 4.1.2 on 2022-12-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0012_expediente_formatosoporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'ordering': ['nombre'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
    ]
