# Generated by Django 4.1.2 on 2022-12-27 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CATALOGOS', '0013_alter_areas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='idUsuarioCreador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
