# Generated by Django 4.1.2 on 2023-01-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0014_alter_expediente_idusuariocreador'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='sistema',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
