# Generated by Django 4.1.2 on 2023-01-08 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CATALOGOS', '0015_expediente_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='idAreaProcedenciaN',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.areas'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='idAreaSIO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.areasio'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='idMacroproceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.macroproceso'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='idProceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.proceso'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='idSerie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.serie'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='idTipoMacroproceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.tipomacroproceso'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='idUsuarioCreador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
