# Generated by Django 4.1.2 on 2023-01-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0016_alter_expediente_idareaprocedencian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
