# Generated by Django 4.1.2 on 2023-01-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0017_alter_areas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='institucionMig',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
