# Generated by Django 4.1.2 on 2023-01-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0018_alter_expediente_institucionmig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='institucionMig',
            field=models.CharField(blank=True, max_length=68655, null=True),
        ),
    ]
