# Generated by Django 4.1.2 on 2023-01-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0019_alter_expediente_institucionmig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fechaModificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
