# Generated by Django 4.1.2 on 2023-01-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0021_alter_expediente_resumencontenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='resumenContenido',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
