# Generated by Django 4.1.2 on 2023-01-18 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0022_alter_expediente_resumencontenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='idInstitucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.institucionesfinancieras'),
        ),
    ]
