# Generated by Django 4.1.2 on 2023-01-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0023_alter_expediente_idinstitucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
