# Generated by Django 4.1.2 on 2023-01-31 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0024_alter_expediente_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='idInstitucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.institucionesfinancieras'),
        ),
    ]
