# Generated by Django 4.1.2 on 2023-02-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0026_alfrescocca'),
    ]

    operations = [
        migrations.AddField(
            model_name='alfrescocca',
            name='idMacroproceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.macroproceso'),
        ),
        migrations.AddField(
            model_name='alfrescocca',
            name='idProceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.proceso'),
        ),
        migrations.AddField(
            model_name='alfrescocca',
            name='idSerie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.serie'),
        ),
        migrations.AddField(
            model_name='alfrescocca',
            name='idTipoMacroproceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.tipomacroproceso'),
        ),
        migrations.AlterField(
            model_name='alfrescocca',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
