# Generated by Django 4.1.2 on 2023-02-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0027_alfrescocca_idmacroproceso_alfrescocca_idproceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alfrescocca',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
