# Generated by Django 4.1.2 on 2023-02-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0028_alter_alfrescocca_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedienteoptions',
            name='folioSIO',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
