# Generated by Django 4.1.2 on 2023-02-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0029_expedienteoptions_foliosio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedienteoptions',
            name='folioSIO',
        ),
        migrations.AddField(
            model_name='alfrescocca',
            name='folioSIO',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
