# Generated by Django 4.1.2 on 2023-02-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0030_remove_expedienteoptions_foliosio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alfrescocca',
            name='folioSIO',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
