# Generated by Django 4.1.2 on 2023-03-27 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0032_alter_expediente_fechacreacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VigenciaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite', models.CharField(max_length=10)),
                ('concentracion', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
                ('idSerie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.serie')),
            ],
        ),
    ]
