# Generated by Django 4.1.2 on 2023-03-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0033_vigenciadocumental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vigenciadocumental',
            name='concentracion',
        ),
        migrations.RemoveField(
            model_name='vigenciadocumental',
            name='idSerie',
        ),
        migrations.RemoveField(
            model_name='vigenciadocumental',
            name='total',
        ),
        migrations.RemoveField(
            model_name='vigenciadocumental',
            name='tramite',
        ),
        migrations.AddField(
            model_name='vigenciadocumental',
            name='fechaActualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigenciadocumental',
            name='fechaFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigenciadocumental',
            name='fechaInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigenciadocumental',
            name='idEstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.estatuscatalogo'),
        ),
        migrations.AddField(
            model_name='vigenciadocumental',
            name='nombre',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='SerieVigenciaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anios', models.IntegerField(blank=True, null=True)),
                ('meses', models.IntegerField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('fechaInicio', models.DateTimeField(blank=True, null=True)),
                ('fechaActualizacion', models.DateTimeField(blank=True, null=True)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('idEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.estatuscatalogo')),
                ('idSerie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.serie')),
                ('idVigenciaDocumental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.vigenciadocumental')),
            ],
        ),
    ]
