# Generated by Django 4.1.2 on 2023-03-28 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0034_remove_vigenciadocumental_concentracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoracionPrimaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True)),
                ('fechaActualizacion', models.DateTimeField(blank=True, null=True)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('fechaInicio', models.DateTimeField(blank=True, null=True)),
                ('idEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.estatuscatalogo')),
            ],
        ),
        migrations.CreateModel(
            name='SerieValoracionPrimaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(blank=True, null=True)),
                ('fechaActualizacion', models.DateTimeField(blank=True, null=True)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('idEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.estatuscatalogo')),
                ('idSerie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.serie')),
                ('idValoracionPrimaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.vigenciadocumental')),
            ],
        ),
    ]
