# Generated by Django 4.1.2 on 2023-04-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0035_valoracionprimaria_serievaloracionprimaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serievaloracionprimaria',
            name='idValoracionPrimaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.valoracionprimaria'),
        ),
    ]
