# Generated by Django 4.1.2 on 2023-05-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0036_alter_serievaloracionprimaria_idvaloracionprimaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='idAreaSIO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.areasio'),
        ),
    ]
