# Generated by Django 4.1.2 on 2023-05-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0037_alter_expediente_idareasio'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasio',
            name='nombreCorto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
