# Generated by Django 4.1.2 on 2024-02-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0038_areasio_nombrecorto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='idAreaProcedenciaA',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
