# Generated by Django 4.1.2 on 2022-11-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='consulta',
            new_name='consulta_completa',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='digitalizacion',
            new_name='consulta_parcial',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='glosa',
            new_name='crear_expedientes',
        ),
        migrations.AddField(
            model_name='user',
            name='eliminar_expedientes',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subir_documentos',
            field=models.BooleanField(null=True),
        ),
    ]
