# Generated by Django 4.1.2 on 2022-11-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0002_rename_consulta_user_consulta_completa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='consulta_parcial',
        ),
    ]
