# Generated by Django 4.1.2 on 2022-12-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0011_remove_tipodocumental_tipo_macroproceso'),
        ('USER_APP', '0003_remove_user_consulta_parcial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=600, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.expediente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.areas')),
            ],
        ),
    ]
