# Generated by Django 4.1.2 on 2022-12-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0004_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
