# Generated by Django 4.1.2 on 2023-01-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0014_alter_expediente_idusuariocreador'),
        ('USER_APP', '0005_alter_bitacora_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas_asociada',
            field=models.ManyToManyField(to='CATALOGOS.areas'),
        ),
    ]
