# Generated by Django 4.1.2 on 2023-01-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0006_user_areas_asociada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='areas_asociada',
            new_name='areas_asociadas',
        ),
    ]
