# Generated by Django 4.1.2 on 2023-01-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0007_rename_areas_asociada_user_areas_asociadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_cuenta',
            field=models.CharField(choices=[('test', 'Test'), ('generica', 'Generica'), ('personal', 'Personal')], max_length=256),
        ),
    ]
