# Generated by Django 4.1.2 on 2023-01-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0008_alter_user_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_cuenta',
            field=models.CharField(choices=[('test', 'Test'), ('generica', 'Genérica'), ('personal', 'Personal')], max_length=256),
        ),
    ]
