# Generated by Django 4.1.2 on 2023-01-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0009_alter_user_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consulta_completa',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='crear_expedientes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='eliminar_expedientes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subir_documentos',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_cuenta',
            field=models.CharField(choices=[('test', 'Test'), ('generica', 'Genérica'), ('personal', 'Personal')], default='personal', max_length=256),
        ),
    ]
