# Generated by Django 4.1.2 on 2023-04-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0011_user_migrar_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carga_masiva',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
