# Generated by Django 4.1.2 on 2023-06-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0012_user_carga_masiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eliminar_documentos',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
