# Generated by Django 4.1.2 on 2023-08-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0013_user_eliminar_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_uau',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
