# Generated by Django 4.1.2 on 2025-06-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0014_user_dashboard_uau'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificar_expediente',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
