# Generated by Django 4.1.2 on 2022-11-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DIGITALIZACION_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo Documental',
                'verbose_name_plural': 'Tipos Documentales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DIGITALIZACION_APP.tipodocumental'),
        ),
    ]
