# Generated by Django 4.1.2 on 2022-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0009_expediente_idestatus'),
        ('DIGITALIZACION_APP', '0003_tipodocumentalasignaciones_alter_document_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumentalasignaciones',
            options={'verbose_name': 'Tipo Documental', 'verbose_name_plural': 'Tipos Documentales'},
        ),
        migrations.RemoveField(
            model_name='tipodocumentalasignaciones',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='tipodocumentalasignaciones',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='tipodocumentalasignaciones',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tipodocumentalasignaciones',
            name='tipo_macroproceso',
            field=models.ManyToManyField(to='CATALOGOS.tipomacroproceso'),
        ),
    ]
