# Generated by Django 4.1.2 on 2022-11-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DIGITALIZACION_APP', '0004_alter_tipodocumentalasignaciones_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoDocumentalAsignaciones',
        ),
    ]
