# Generated by Django 4.1.2 on 2022-12-25 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0013_alter_areas_options'),
        ('DIGITALIZACION_APP', '0005_delete_tipodocumentalasignaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='OriginalDocuments',
        ),
        migrations.CreateModel(
            name='SplitDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.expediente')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.tipodocumental')),
            ],
            options={
                'verbose_name': 'Split Document',
                'verbose_name_plural': 'Split Documents',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Portadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.expediente')),
            ],
            options={
                'verbose_name': 'Portada',
                'verbose_name_plural': 'Portadas',
                'ordering': ['-date_creation'],
            },
        ),
    ]
