# Generated by Django 4.1.2 on 2022-12-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DIGITALIZACION_APP', '0007_originaldocuments_user_portadas_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originaldocuments',
            name='tipo',
        ),
    ]
