# Generated by Django 4.1.2 on 2023-01-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIGITALIZACION_APP', '0008_remove_originaldocuments_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originaldocuments',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portadas',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portadas',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='splitdocuments',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='splitdocuments',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
