# Generated by Django 4.1.2 on 2023-02-24 17:15

import DIGITALIZACION_APP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIGITALIZACION_APP', '0009_alter_originaldocuments_title_alter_portadas_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originaldocuments',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to=DIGITALIZACION_APP.models.image_upload_path),
        ),
    ]
