# Generated by Django 4.1.2 on 2023-04-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0036_alter_serievaloracionprimaria_idvaloracionprimaria'),
        ('DIGITALIZACION_APP', '0010_alter_originaldocuments_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('last_edit_date', models.DateTimeField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.expediente')),
            ],
            options={
                'verbose_name': 'Integrated File',
                'verbose_name_plural': 'Integrated Files',
                'ordering': ['-date_creation'],
            },
        ),
    ]
