# Generated by Django 4.1.2 on 2023-04-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DIGITALIZACION_APP', '0011_integratedfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntegratedFiles',
        ),
    ]
