# Generated by Django 4.1.2 on 2023-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIGITALIZACION_APP', '0012_delete_integratedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitdocuments',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
