# Generated by Django 4.1.2 on 2024-03-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIGITALIZACION_APP', '0013_splitdocuments_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitdocuments',
            name='docIndex',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
