# Generated by Django 4.1.2 on 2025-06-10 01:23

import DIGITALIZACION_APP.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATALOGOS', '0039_alter_expediente_fechacreacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DIGITALIZACION_APP', '0014_splitdocuments_docindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificacionExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_certificacion', models.DateTimeField(auto_now_add=True)),
                ('folio_expediente', models.CharField(max_length=500)),
                ('recurrente', models.CharField(max_length=500)),
                ('pdf_certificado', models.FileField(blank=True, null=True, upload_to=DIGITALIZACION_APP.models.certificacion_upload_path)),
                ('pdf_recurso_revision', models.FileField(blank=True, null=True, upload_to=DIGITALIZACION_APP.models.certificacion_upload_path)),
                ('fecha_recepcion_recurso', models.DateField(blank=True, null=True)),
                ('fecha_envio_dgsl', models.DateField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('pdf_certificado_firmado', models.FileField(blank=True, null=True, upload_to=DIGITALIZACION_APP.models.certificacion_upload_path)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CATALOGOS.areas')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CATALOGOS.expediente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificación de Expediente',
                'verbose_name_plural': 'Certificaciones de Expedientes',
                'ordering': ['-fecha_certificacion'],
            },
        ),
    ]
